/**
 * Import State Compliance Specification
 *
 * Reads a JSON compliance specification file and automatically creates:
 * - Extraction profiles
 * - Compliance rules
 * - Disclosure requirements
 * - Timing rules
 * - Blocking gates
 *
 * Usage:
 *   npx ts-node src/scripts/importStateCompliance.ts <path-to-json>
 *
 * Example:
 *   npx ts-node src/scripts/importStateCompliance.ts compliance-specs/texas-harris.json
 */

import fs from 'fs';
import path from 'path';
import { DataTypes } from 'sequelize';
import sequelize from '../config/database';
import ComplianceExtractionProfile from '../models/ComplianceExtractionProfile';

interface StateComplianceSpec {
  state: string;
  county: string;
  version: string;
  metadata?: any;
  contacts?: any[];
  documents?: any[];
  rules?: ComplianceRule[];
  disclosures?: Disclosure[];
  timingRules?: TimingRule[];
  extractionProfiles?: ExtractionProfile[];
  scoringRules?: ScoringRules;
  blockingGates?: BlockingGate[];
  databaseSchema?: any;
}

interface ComplianceRule {
  ruleId: string;
  phase: number;
  description: string;
  validationType: string;
  validation: any;
  blocking: boolean;
  severity: string;
  errorMessage: string;
  remediation?: string;
}

interface Disclosure {
  disclosureId: string;
  name: string;
  description: string;
  legalCitation?: string;
  required: boolean;
  substanceRequired?: boolean;
  keywords?: string[];
  regexPattern?: string;
}

interface TimingRule {
  ruleId: string;
  description: string;
  eventA: string;
  eventB: string;
  relationship: string;
  dayBuffer?: number;
  blocking: boolean;
  blocksPhase?: number;
}

interface ExtractionProfile {
  state: string;
  category: string;
  name: string;
  description?: string;
  fieldLabels: Record<string, string[]>;
  regexHints?: Record<string, string>;
  promptOverrides?: string;
  requiredFields?: string[];
  minConfidence?: number;
  priority?: number;
}

interface ScoringRules {
  green: any;
  yellow: any;
  red: any;
}

interface BlockingGate {
  gateId: string;
  name: string;
  phase: number;
  blocksPhase: number;
  condition: string;
  errorMessage: string;
}

async function importStateCompliance(filePath: string): Promise<void> {
  console.log('🚀 Importing State Compliance Specification\n');
  console.log('='.repeat(80));

  // Read JSON file
  console.log(`📖 Reading file: ${filePath}`);
  if (!fs.existsSync(filePath)) {
    throw new Error(`File not found: ${filePath}`);
  }

  const fileContent = fs.readFileSync(filePath, 'utf-8');
  const spec: StateComplianceSpec = JSON.parse(fileContent);

  console.log(`✅ Loaded specification for ${spec.state} (${spec.county})`);
  console.log(`   Version: ${spec.version}`);
  if (spec.metadata?.generatedBy) {
    console.log(`   Generated by: ${spec.metadata.generatedBy}`);
  }
  console.log();

  // Initialize database
  console.log('🔌 Connecting to database...');
  const { default: sequelize } = await import('../config/database');
  await sequelize.authenticate();
  console.log('✅ Database connected\n');

  // Import extraction profiles
  if (spec.extractionProfiles && spec.extractionProfiles.length > 0) {
    console.log('📋 Importing Extraction Profiles...');
    for (const profile of spec.extractionProfiles) {
      try {
        const [created, wasCreated] = await ComplianceExtractionProfile.findOrCreate({
          where: {
            state: profile.state,
            category: profile.category,
          },
          defaults: {
            state: profile.state,
            category: profile.category,
            name: profile.name,
            description: profile.description || '',
            fieldLabels: profile.fieldLabels,
            regexHints: profile.regexHints || {},
            promptOverrides: profile.promptOverrides || undefined,
            requiredFields: profile.requiredFields || [],
            minConfidence: profile.minConfidence || 0.75,
            enabled: true,
            priority: profile.priority || 100,
          },
        });

        if (!wasCreated) {
          // Update existing
          await created.update({
            name: profile.name,
            description: profile.description || '',
            fieldLabels: profile.fieldLabels,
            regexHints: profile.regexHints || {},
            promptOverrides: profile.promptOverrides || undefined,
            requiredFields: profile.requiredFields || [],
            minConfidence: profile.minConfidence || 0.75,
            priority: profile.priority || 100,
          });
          console.log(`   ↻ Updated: ${profile.name}`);
        } else {
          console.log(`   ✓ Created: ${profile.name}`);
        }
      } catch (error) {
        console.error(`   ✗ Failed: ${profile.name}`, error);
      }
    }
    console.log(`✅ Imported ${spec.extractionProfiles.length} extraction profiles\n`);
  }

  // Store compliance rules in database (as configuration)
  if (spec.rules && spec.rules.length > 0) {
    console.log('⚖️  Importing Compliance Rules...');

    // Use raw SQL for upsert since the table schema is complex
    const upsertQuery = `
      INSERT INTO state_compliance_configs
        (state, county, version, contacts, documents, rules, disclosures,
         "timingRules", "extractionProfiles", "scoringRules", "blockingGates",
         "isActive", "createdAt", "updatedAt")
      VALUES
        ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, true, NOW(), NOW())
      ON CONFLICT (state) DO UPDATE SET
        county = EXCLUDED.county,
        version = EXCLUDED.version,
        contacts = EXCLUDED.contacts,
        documents = EXCLUDED.documents,
        rules = EXCLUDED.rules,
        disclosures = EXCLUDED.disclosures,
        "timingRules" = EXCLUDED."timingRules",
        "extractionProfiles" = EXCLUDED."extractionProfiles",
        "scoringRules" = EXCLUDED."scoringRules",
        "blockingGates" = EXCLUDED."blockingGates",
        "updatedAt" = NOW()
      RETURNING state;
    `;

    await sequelize.query(upsertQuery, {
      bind: [
        spec.state,
        spec.county,
        spec.version,
        JSON.stringify(spec.contacts || []),
        JSON.stringify(spec.documents || []),
        JSON.stringify(spec.rules || []),
        JSON.stringify(spec.disclosures || []),
        JSON.stringify(spec.timingRules || []),
        JSON.stringify(spec.extractionProfiles || []),
        JSON.stringify(spec.scoringRules || {}),
        JSON.stringify(spec.blockingGates || []),
      ],
    });

    console.log(`   ✓ Stored ${spec.rules.length} compliance rules`);
    if (spec.disclosures) {
      console.log(`   ✓ Stored ${spec.disclosures.length} disclosure requirements`);
    }
    if (spec.timingRules) {
      console.log(`   ✓ Stored ${spec.timingRules.length} timing rules`);
    }
    if (spec.blockingGates) {
      console.log(`   ✓ Stored ${spec.blockingGates.length} blocking gates`);
    }
    console.log(`✅ Compliance rules imported\n`);
  }

  // Summary
  console.log('='.repeat(80));
  console.log('📊 IMPORT SUMMARY');
  console.log('='.repeat(80));
  console.log();
  console.log(`State: ${spec.state}`);
  console.log(`County: ${spec.county}`);
  console.log(`Version: ${spec.version}`);
  console.log();
  console.log('Imported:');
  console.log(`  ✓ ${spec.extractionProfiles?.length || 0} extraction profiles`);
  console.log(`  ✓ ${spec.rules?.length || 0} compliance rules`);
  console.log(`  ✓ ${spec.disclosures?.length || 0} disclosure requirements`);
  console.log(`  ✓ ${spec.timingRules?.length || 0} timing rules`);
  console.log(`  ✓ ${spec.blockingGates?.length || 0} blocking gates`);
  console.log();
  console.log('='.repeat(80));
  console.log('✅ Import completed successfully!');
  console.log('='.repeat(80));
  console.log();
  console.log('Next steps:');
  console.log(`  1. Test extraction: npm run test:extraction <pdf> ${spec.state} purchase_contract`);
  console.log(`  2. Verify rules in database: SELECT * FROM state_compliance_configs WHERE state='${spec.state}'`);
  console.log(`  3. Start using in your workflow`);
  console.log();

  await sequelize.close();
}

// Run if called directly
if (require.main === module) {
  const filePath = process.argv[2];

  if (!filePath) {
    console.error('❌ Error: File path required');
    console.log();
    console.log('Usage:');
    console.log('  npx ts-node src/scripts/importStateCompliance.ts <path-to-json>');
    console.log();
    console.log('Example:');
    console.log('  npx ts-node src/scripts/importStateCompliance.ts compliance-specs/texas-harris.json');
    process.exit(1);
  }

  importStateCompliance(filePath)
    .then(() => {
      process.exit(0);
    })
    .catch((error) => {
      console.error('\n❌ Import failed:');
      console.error(error);
      process.exit(1);
    });
}

export default importStateCompliance;
