/**
 * Compliance Report Export Service
 *
 * Generates PDF reports and handles email delivery for compliance reports.
 * Uses PDFKit for PDF generation and Resend for email delivery.
 */

import { Resend } from 'resend';
import PDFDocument from 'pdfkit';
import ComplianceReport from '../models/ComplianceReport';
import { ReportData, DealReportData, AlertSummary } from './ComplianceReportService';

class ComplianceReportExportService {
  private resend: Resend | null = null;

  constructor() {
    if (process.env.RESEND_API_KEY) {
      this.resend = new Resend(process.env.RESEND_API_KEY);
    }
  }

  /**
   * Generate PDF report
   */
  async generatePDF(
    report: ComplianceReport,
    data: ReportData,
    summary: ComplianceReport['summary']
  ): Promise<{ pdfBuffer: Buffer; pdfSize: number }> {
    return new Promise((resolve, reject) => {
      const chunks: Buffer[] = [];
      const doc = new PDFDocument({
        size: 'A4',
        margin: 40,
        bufferPages: true,
        info: {
          Title: report.name,
          Author: 'Dispotree Compliance System',
          Subject: 'Compliance Report',
          Creator: 'Dispotree',
        },
      });

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(chunks);
        resolve({ pdfBuffer, pdfSize: pdfBuffer.length });
      });
      doc.on('error', reject);

      // Colors
      const primaryColor = '#10B981'; // Green
      const dangerColor = '#EF4444'; // Red
      const warningColor = '#F59E0B'; // Amber
      const textColor = '#1F2937';
      const mutedColor = '#6B7280';
      const cardBg = '#F9FAFB';

      // Header
      this.renderHeader(doc, report, primaryColor, mutedColor);

      // Executive Summary
      this.renderExecutiveSummary(doc, summary, primaryColor, dangerColor, warningColor, textColor, mutedColor);

      // Alert Summary
      if (data.alerts.total > 0) {
        this.renderAlertSection(doc, data.alerts, primaryColor, dangerColor, warningColor, textColor, mutedColor);
      }

      // Deal Details
      this.renderDealSection(doc, data.deals, primaryColor, dangerColor, warningColor, textColor, mutedColor, cardBg);

      // Audit Log Summary (if included)
      if (data.auditLogs) {
        this.renderAuditLogSection(doc, data.auditLogs, textColor, mutedColor);
      }

      // Compliance Check Summary (if included)
      if (data.complianceChecks) {
        this.renderComplianceCheckSection(doc, data.complianceChecks, primaryColor, textColor, mutedColor);
      }

      // Footer
      this.renderFooter(doc, mutedColor);

      doc.end();
    });
  }

  /**
   * Render PDF header
   */
  private renderHeader(
    doc: PDFKit.PDFDocument,
    report: ComplianceReport,
    primaryColor: string,
    mutedColor: string
  ): void {
    // Logo / Brand
    doc.fontSize(28)
      .fillColor(primaryColor)
      .font('Helvetica-Bold')
      .text('Dispotree', 40, 40);

    doc.fontSize(16)
      .fillColor('#1F2937')
      .font('Helvetica-Bold')
      .text('Compliance Report', 40, 75);

    doc.fontSize(12)
      .fillColor(mutedColor)
      .font('Helvetica')
      .text(report.name, 40, 95);

    if (report.description) {
      doc.fontSize(10)
        .text(report.description, 40, 112, { width: 400 });
    }

    // Report metadata
    const metaY = report.description ? 140 : 115;
    doc.fontSize(9)
      .fillColor(mutedColor)
      .text(`Report Type: ${this.formatReportType(report.reportType)}`, 40, metaY);

    doc.text(`Generated: ${new Date().toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })}`, 40, metaY + 14);

    if (report.generatedByName) {
      doc.text(`Generated by: ${report.generatedByName}`, 40, metaY + 28);
    }

    // Divider line
    doc.moveTo(40, metaY + 50)
      .lineTo(555, metaY + 50)
      .strokeColor('#E5E7EB')
      .stroke();
  }

  /**
   * Render executive summary section
   */
  private renderExecutiveSummary(
    doc: PDFKit.PDFDocument,
    summary: ComplianceReport['summary'],
    primaryColor: string,
    dangerColor: string,
    warningColor: string,
    textColor: string,
    mutedColor: string
  ): void {
    if (!summary) return;

    let yPos = 200;

    doc.fontSize(14)
      .fillColor(textColor)
      .font('Helvetica-Bold')
      .text('Executive Summary', 40, yPos);

    yPos += 30;

    // Summary cards
    const cardWidth = 125;
    const cardHeight = 70;
    const cardGap = 10;

    // Total Deals card
    this.renderSummaryCard(doc, 40, yPos, cardWidth, cardHeight, 'Total Deals', String(summary.totalDeals), mutedColor, textColor);

    // Compliant Deals card
    this.renderSummaryCard(doc, 40 + cardWidth + cardGap, yPos, cardWidth, cardHeight, 'Compliant', String(summary.compliantDeals), primaryColor, textColor);

    // Non-Compliant Deals card
    this.renderSummaryCard(doc, 40 + (cardWidth + cardGap) * 2, yPos, cardWidth, cardHeight, 'Non-Compliant', String(summary.nonCompliantDeals), dangerColor, textColor);

    // Compliance Rate card
    this.renderSummaryCard(doc, 40 + (cardWidth + cardGap) * 3, yPos, cardWidth, cardHeight, 'Compliance Rate', `${summary.complianceRate.toFixed(1)}%`, primaryColor, textColor);

    yPos += cardHeight + 20;

    // Alert counts
    if (summary.criticalAlerts > 0 || summary.highAlerts > 0 || summary.warningAlerts > 0) {
      doc.fontSize(10)
        .fillColor(mutedColor)
        .font('Helvetica')
        .text('Active Alerts: ', 40, yPos, { continued: true });

      if (summary.criticalAlerts > 0) {
        doc.fillColor(dangerColor).text(`${summary.criticalAlerts} Critical  `, { continued: true });
      }
      if (summary.highAlerts > 0) {
        doc.fillColor(warningColor).text(`${summary.highAlerts} High  `, { continued: true });
      }
      if (summary.warningAlerts > 0) {
        doc.fillColor(mutedColor).text(`${summary.warningAlerts} Warning`, { continued: false });
      }
    }
  }

  /**
   * Render a summary card
   */
  private renderSummaryCard(
    doc: PDFKit.PDFDocument,
    x: number,
    y: number,
    width: number,
    height: number,
    label: string,
    value: string,
    valueColor: string,
    textColor: string
  ): void {
    doc.roundedRect(x, y, width, height, 6)
      .fillColor('#F9FAFB')
      .fill();

    doc.fontSize(9)
      .fillColor('#6B7280')
      .font('Helvetica')
      .text(label, x + 10, y + 12, { width: width - 20, align: 'center' });

    doc.fontSize(24)
      .fillColor(valueColor)
      .font('Helvetica-Bold')
      .text(value, x + 10, y + 30, { width: width - 20, align: 'center' });
  }

  /**
   * Render alert section
   */
  private renderAlertSection(
    doc: PDFKit.PDFDocument,
    alerts: AlertSummary,
    primaryColor: string,
    dangerColor: string,
    warningColor: string,
    textColor: string,
    mutedColor: string
  ): void {
    doc.addPage();

    doc.fontSize(14)
      .fillColor(textColor)
      .font('Helvetica-Bold')
      .text('Alert Summary', 40, 40);

    let yPos = 70;

    // Alert counts by severity
    doc.fontSize(10)
      .fillColor(mutedColor)
      .font('Helvetica')
      .text('Alerts by Severity:', 40, yPos);

    yPos += 20;

    const severityData = [
      { label: 'Critical', count: alerts.bySeverity.critical, color: dangerColor },
      { label: 'High', count: alerts.bySeverity.high, color: warningColor },
      { label: 'Warning', count: alerts.bySeverity.warning, color: '#F59E0B' },
      { label: 'Info', count: alerts.bySeverity.info, color: '#3B82F6' },
    ];

    for (const item of severityData) {
      doc.roundedRect(40, yPos, 100, 25, 4)
        .fillColor(item.color + '20')
        .fill();

      doc.fontSize(10)
        .fillColor(item.color)
        .font('Helvetica-Bold')
        .text(`${item.label}: ${item.count}`, 50, yPos + 7);

      yPos += 30;
    }

    // Recent alerts
    if (alerts.recentAlerts.length > 0) {
      yPos += 20;
      doc.fontSize(12)
        .fillColor(textColor)
        .font('Helvetica-Bold')
        .text('Recent Alerts', 40, yPos);

      yPos += 20;

      for (const alert of alerts.recentAlerts.slice(0, 5)) {
        const severityColor = alert.severity === 'critical' ? dangerColor :
          alert.severity === 'high' ? warningColor : mutedColor;

        doc.roundedRect(40, yPos, 515, 50, 4)
          .fillColor('#F9FAFB')
          .fill();

        doc.fontSize(10)
          .fillColor(severityColor)
          .font('Helvetica-Bold')
          .text(`[${alert.severity.toUpperCase()}]`, 50, yPos + 8, { continued: true });

        doc.fillColor(textColor)
          .font('Helvetica')
          .text(` ${alert.title}`, { continued: false });

        doc.fontSize(9)
          .fillColor(mutedColor)
          .text(alert.message, 50, yPos + 25, { width: 490 });

        yPos += 60;

        if (yPos > 700) {
          doc.addPage();
          yPos = 40;
        }
      }
    }
  }

  /**
   * Render deal section
   */
  private renderDealSection(
    doc: PDFKit.PDFDocument,
    deals: DealReportData[],
    primaryColor: string,
    dangerColor: string,
    warningColor: string,
    textColor: string,
    mutedColor: string,
    cardBg: string
  ): void {
    doc.addPage();

    doc.fontSize(14)
      .fillColor(textColor)
      .font('Helvetica-Bold')
      .text('Deal Details', 40, 40);

    let yPos = 70;

    for (const deal of deals) {
      if (yPos > 680) {
        doc.addPage();
        yPos = 40;
      }

      // Deal card
      doc.roundedRect(40, yPos, 515, 100, 6)
        .fillColor(cardBg)
        .fill();

      // Status indicator
      const statusColor = deal.complianceStatus === 'Green' ? primaryColor :
        deal.complianceStatus === 'Red' ? dangerColor : warningColor;

      doc.roundedRect(480, yPos + 10, 60, 24, 4)
        .fillColor(statusColor)
        .fill();

      doc.fontSize(9)
        .fillColor('#FFFFFF')
        .font('Helvetica-Bold')
        .text(deal.complianceStatus, 485, yPos + 16, { width: 50, align: 'center' });

      // Address
      doc.fontSize(12)
        .fillColor(textColor)
        .font('Helvetica-Bold')
        .text(deal.address || 'Unknown Address', 55, yPos + 12, { width: 400 });

      doc.fontSize(10)
        .fillColor(mutedColor)
        .font('Helvetica')
        .text(`${deal.city}, ${deal.state} ${deal.zip}`, 55, yPos + 28);

      // Property ID
      doc.fontSize(9)
        .text(`Property ID: ${deal.propertyId}`, 55, yPos + 45);

      // Latest check info
      if (deal.latestCheck) {
        doc.text(`Last Check: ${new Date(deal.latestCheck.checkedAt).toLocaleDateString()} - ` +
          `${deal.latestCheck.passedRules} passed, ${deal.latestCheck.failedRules} failed`, 55, yPos + 58);
      }

      // Alert counts
      if (deal.alerts.critical > 0 || deal.alerts.high > 0 || deal.alerts.warning > 0) {
        doc.fontSize(9)
          .text('Alerts: ', 55, yPos + 75, { continued: true });

        if (deal.alerts.critical > 0) {
          doc.fillColor(dangerColor).text(`${deal.alerts.critical} critical `, { continued: true });
        }
        if (deal.alerts.high > 0) {
          doc.fillColor(warningColor).text(`${deal.alerts.high} high `, { continued: true });
        }
        if (deal.alerts.warning > 0) {
          doc.fillColor(mutedColor).text(`${deal.alerts.warning} warning`, { continued: false });
        }
      }

      yPos += 110;
    }
  }

  /**
   * Render audit log section
   */
  private renderAuditLogSection(
    doc: PDFKit.PDFDocument,
    auditLogs: ReportData['auditLogs'],
    textColor: string,
    mutedColor: string
  ): void {
    if (!auditLogs) return;

    doc.addPage();

    doc.fontSize(14)
      .fillColor(textColor)
      .font('Helvetica-Bold')
      .text('Audit Log Summary', 40, 40);

    let yPos = 70;

    doc.fontSize(10)
      .fillColor(mutedColor)
      .font('Helvetica')
      .text(`Total Entries: ${auditLogs.totalEntries}`, 40, yPos);

    yPos += 20;

    // Categories
    doc.fontSize(11)
      .fillColor(textColor)
      .font('Helvetica-Bold')
      .text('By Category:', 40, yPos);

    yPos += 15;

    for (const [category, count] of Object.entries(auditLogs.byCategory)) {
      doc.fontSize(9)
        .fillColor(mutedColor)
        .font('Helvetica')
        .text(`• ${category}: ${count}`, 50, yPos);
      yPos += 14;
    }

    yPos += 10;

    // Outcomes
    doc.fontSize(11)
      .fillColor(textColor)
      .font('Helvetica-Bold')
      .text('By Outcome:', 40, yPos);

    yPos += 15;

    for (const [outcome, count] of Object.entries(auditLogs.byOutcome)) {
      doc.fontSize(9)
        .fillColor(mutedColor)
        .font('Helvetica')
        .text(`• ${outcome}: ${count}`, 50, yPos);
      yPos += 14;
    }
  }

  /**
   * Render compliance check section
   */
  private renderComplianceCheckSection(
    doc: PDFKit.PDFDocument,
    checks: ReportData['complianceChecks'],
    primaryColor: string,
    textColor: string,
    mutedColor: string
  ): void {
    if (!checks) return;

    doc.addPage();

    doc.fontSize(14)
      .fillColor(textColor)
      .font('Helvetica-Bold')
      .text('Compliance Check Summary', 40, 40);

    let yPos = 70;

    doc.fontSize(10)
      .fillColor(mutedColor)
      .font('Helvetica')
      .text(`Total Checks: ${checks.total}`, 40, yPos);

    doc.text(`Passed: ${checks.passed}`, 40, yPos + 14);
    doc.text(`Failed: ${checks.failed}`, 40, yPos + 28);

    doc.fillColor(primaryColor)
      .font('Helvetica-Bold')
      .text(`Average Pass Rate: ${checks.averagePassRate.toFixed(1)}%`, 40, yPos + 48);
  }

  /**
   * Render footer
   */
  private renderFooter(doc: PDFKit.PDFDocument, mutedColor: string): void {
    const pages = doc.bufferedPageRange();

    for (let i = 0; i < pages.count; i++) {
      doc.switchToPage(i);

      doc.fontSize(8)
        .fillColor(mutedColor)
        .font('Helvetica')
        .text(
          `Page ${i + 1} of ${pages.count} | Generated by Dispotree Compliance System`,
          40,
          doc.page.height - 30,
          { align: 'center', width: 515 }
        );
    }
  }

  /**
   * Format report type for display
   */
  private formatReportType(type: string): string {
    const types: Record<string, string> = {
      deal: 'Deal Report',
      portfolio: 'Portfolio Report',
      time_period: 'Time Period Report',
      audit: 'Audit Report',
      custom: 'Custom Report',
    };
    return types[type] || type;
  }

  /**
   * Generate CSV export
   */
  generateCSV(data: ReportData): string {
    const headers = [
      'Property ID',
      'Address',
      'City',
      'State',
      'Zip',
      'Compliance Status',
      'Approval Status',
      'Passed Rules',
      'Failed Rules',
      'Critical Alerts',
      'High Alerts',
      'Warning Alerts',
      'Last Check Date',
      'Created At',
      'Updated At',
    ];

    const rows = data.deals.map(deal => [
      deal.propertyId,
      this.escapeCSV(deal.address),
      this.escapeCSV(deal.city),
      deal.state,
      deal.zip,
      deal.complianceStatus,
      deal.approvalStatus,
      deal.latestCheck?.passedRules || 0,
      deal.latestCheck?.failedRules || 0,
      deal.alerts.critical,
      deal.alerts.high,
      deal.alerts.warning,
      deal.latestCheck?.checkedAt ? new Date(deal.latestCheck.checkedAt).toLocaleDateString() : '',
      new Date(deal.createdAt).toLocaleDateString(),
      new Date(deal.updatedAt).toLocaleDateString(),
    ].join(','));

    return [headers.join(','), ...rows].join('\n');
  }

  /**
   * Escape CSV field
   */
  private escapeCSV(value: string): string {
    if (!value) return '';
    if (value.includes(',') || value.includes('"') || value.includes('\n')) {
      return `"${value.replace(/"/g, '""')}"`;
    }
    return value;
  }

  /**
   * Send report via email
   */
  async sendReportEmail(
    report: ComplianceReport,
    recipients: string[]
  ): Promise<{ success: boolean; message: string }> {
    if (!this.resend) {
      console.log('Resend not configured, logging email request');
      return { success: false, message: 'Email service not configured' };
    }

    if (!report.summary || !report.reportData) {
      return { success: false, message: 'Report data not available' };
    }

    try {
      // Regenerate PDF for attachment
      const { pdfBuffer } = await this.generatePDF(
        report,
        report.reportData as ReportData,
        report.summary
      );

      // Generate CSV
      const csvContent = this.generateCSV(report.reportData as ReportData);

      await this.resend.emails.send({
        from: 'Dispotree <compliance@dispotree.com>',
        to: recipients,
        subject: `Compliance Report: ${report.name}`,
        html: this.generateEmailHTML(report),
        attachments: [
          {
            filename: `compliance-report-${report.id}.pdf`,
            content: pdfBuffer.toString('base64'),
          },
          {
            filename: `compliance-report-${report.id}.csv`,
            content: Buffer.from(csvContent).toString('base64'),
          },
        ],
      });

      return { success: true, message: 'Report email sent successfully' };
    } catch (error) {
      console.error('Failed to send report email:', error);
      return {
        success: false,
        message: error instanceof Error ? error.message : 'Failed to send email',
      };
    }
  }

  /**
   * Generate email HTML
   */
  private generateEmailHTML(report: ComplianceReport): string {
    const summary = report.summary!;

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 0; background-color: #f4f4f5; }
          .container { max-width: 600px; margin: 0 auto; padding: 40px 20px; }
          .card { background: white; border-radius: 12px; padding: 32px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05); }
          .logo { font-size: 28px; font-weight: bold; color: #10B981; margin-bottom: 24px; }
          h1 { font-size: 24px; color: #1f2937; margin: 0 0 16px; }
          p { color: #6b7280; line-height: 1.6; margin: 0 0 16px; }
          .stats { background: #f9fafb; border-radius: 8px; padding: 20px; margin: 24px 0; }
          .stat-row { display: flex; justify-content: space-between; margin-bottom: 12px; }
          .stat-label { color: #6b7280; font-size: 14px; }
          .stat-value { font-weight: bold; color: #1f2937; }
          .stat-green { color: #10B981; }
          .stat-red { color: #EF4444; }
          .stat-amber { color: #F59E0B; }
          .attachments { background: #ecfdf5; border-radius: 8px; padding: 16px; margin-top: 24px; }
          .footer { text-align: center; margin-top: 32px; color: #9ca3af; font-size: 12px; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="card">
            <div class="logo">Dispotree</div>
            <h1>Compliance Report</h1>
            <p><strong>${report.name}</strong></p>
            ${report.description ? `<p>${report.description}</p>` : ''}

            <div class="stats">
              <div class="stat-row">
                <span class="stat-label">Total Deals</span>
                <span class="stat-value">${summary.totalDeals}</span>
              </div>
              <div class="stat-row">
                <span class="stat-label">Compliant</span>
                <span class="stat-value stat-green">${summary.compliantDeals}</span>
              </div>
              <div class="stat-row">
                <span class="stat-label">Non-Compliant</span>
                <span class="stat-value stat-red">${summary.nonCompliantDeals}</span>
              </div>
              <div class="stat-row">
                <span class="stat-label">Pending</span>
                <span class="stat-value stat-amber">${summary.pendingDeals}</span>
              </div>
              <div class="stat-row">
                <span class="stat-label">Compliance Rate</span>
                <span class="stat-value stat-green">${summary.complianceRate.toFixed(1)}%</span>
              </div>
            </div>

            ${summary.criticalAlerts > 0 ? `
              <div style="background: #FEF2F2; border-radius: 8px; padding: 16px; margin-top: 16px;">
                <p style="color: #EF4444; margin: 0;"><strong>⚠️ ${summary.criticalAlerts} Critical Alert${summary.criticalAlerts > 1 ? 's' : ''}</strong></p>
              </div>
            ` : ''}

            <div class="attachments">
              <p style="margin: 0; font-weight: 600; color: #065f46;">Attachments:</p>
              <p style="margin: 8px 0 0; color: #047857;">📄 PDF Report & CSV Data</p>
            </div>
          </div>

          <div class="footer">
            <p>Dispotree - B2B Real Estate Wholesale Platform</p>
            <p>Generated: ${new Date().toLocaleString()}</p>
          </div>
        </div>
      </body>
      </html>
    `;
  }
}

export const complianceReportExportService = new ComplianceReportExportService();
export default complianceReportExportService;
