-- Insert sample property data
INSERT INTO properties (
    "propertyId",
    "liveOnHubzu",
    "propertyOwnership",
    "propertyType",
    address,
    city,
    state,
    zip,
    county,
    "occupancyStatus",
    "occupancyDetails",
    "monthlyRent",
    "deliveredVacant",
    "reservePrice",
    syndication,
    "bedroomCount",
    "bathroomCount",
    "livingSpaceSqFt",
    "lotSizeSqFt",
    "yearBuilt",
    hoa,
    "hoaDuesAmount",
    "propertyContracts",
    "wholesalerLlcName",
    "llcOwnerName",
    "llcBusinessAddress",
    "llcOwnerEmail",
    "knownMaterialDefects",
    "propertyListingDescription",
    roof,
    sewer,
    electric,
    water,
    "foundationType",
    "typeOfRehab"
) VALUES
(
    'PROP-001',
    true,
    'LLC',
    'Single Family',
    '{"houseNumber": "1234", "street": "Main Street"}',
    'Dallas',
    'TX',
    '75201',
    'Dallas County',
    'Vacant',
    'Property is vacant and ready for rehab',
    1800.00,
    true,
    250000,
    ARRAY['Zillow', 'Realtor'],
    3,
    2,
    1450,
    6000,
    1985,
    true,
    50.00,
    'Standard purchase contract with assignable clause',
    'Texas Homes LLC',
    'John Doe',
    '123 Business Rd, Dallas, TX 75201',
    'john.doe@texashomes.com',
    'None known, property inspection recommended',
    'Great investment opportunity in Dallas! This 3 bedroom, 2 bathroom home needs cosmetic updates but has great potential.',
    'Asphalt Shingle',
    'Public Sewer',
    '100 Amp Circuit Breaker',
    'Public Water',
    'Slab',
    'Cosmetic'
),
(
    'PROP-002',
    false,
    'Individual',
    'Townhouse',
    '{"houseNumber": "5678", "street": "Oak Avenue"}',
    'Houston',
    'TX',
    '77002',
    'Harris County',
    'Tenant Occupied',
    'Current tenant on month-to-month lease, can be vacated with 30 days notice',
    2200.00,
    false,
    185000,
    ARRAY['Trulia'],
    2,
    2,
    1200,
    3500,
    2005,
    false,
    null,
    'Standard Texas Real Estate Commission contract',
    null,
    null,
    null,
    null,
    'Minor water damage in master bathroom',
    'Well-maintained townhouse in desirable Houston area. Currently tenant occupied generating income.',
    'Composition',
    'Public Sewer',
    '200 Amp Circuit Breaker',
    'Public Water',
    'Pier and Beam',
    'Minimal'
);

-- Insert sample user
INSERT INTO users (
    email,
    password,
    firstName,
    lastName,
    role
) VALUES (
    'admin@dispotree.com',
    '$2b$10$r.8t.EG8ewdMzN2UUiIInOjFBEA2WQp3mjXp5V5V5v5v5v5v5v5v5O',
    'Admin',
    'User',
    'admin'
);